# Site settings
title: Andy's blog
email: cao_huayu@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Not afraid, just keep going and follow my heart!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andyopen.com" # the base hostname & protocol for your site
twitter_username: cao_huayu
github_username:  andycao

# Build settings
markdown: kramdown
